# Dependencies
markdown:         redcarpet
highlighter:      pygments


# Permalinks
permalink:        pretty
relative_permalinks: false
# Setup
title:            "Sophia 
                  Alignment: Model-Self-Defined Step Enhanced Intelligence Alignment"
tagline:          
#description:      'SophiaAlignment aims to enhance the performance of language models across various domains by aligning the reasoning process with the perplexity metrics of language models through Process Supervision, Inference Framework, and Reinforcement Learning.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'SophiaAlignment-organization'
  #url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.0.1

github:
  repo:           https://github.com/poole/hyde
